version: "3.9"

services:
    load_balancer:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./lbdefault.conf:/etc/nginx/nginx.conf
        depends_on:
            - db
            - web1
            - web2
            - web3

    web1:
        image: web1
        restart: always
        build:
            context: app
            dockerfile: Dockerfile
        expose:
            - "80"
        environment:
            - WORKER_ID=1
        depends_on:
            - db

    web2:
        image: web2
        restart: always
        build:
            context: app
            dockerfile: Dockerfile
        expose:
            - "80"
        environment:
            - WORKER_ID=2
        depends_on:
            - db

    web3:
        image: web3
        restart: always
        build:
            context: app
            dockerfile: Dockerfile
        expose:
            - "80"
        environment:
            - WORKER_ID=3
        depends_on:
            - db
    
    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=abcd1234
        restart: always
        volumes:
            - db_vol:/var/lib/mysql

volumes:
    db_vol: